arch:
  - amd64
  - ppc64le
language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

env:
  - DJANGO_VERSION=2.2.9
  - DJANGO_VERSION=3.0.2

install:
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q develop

script:
  - cd example_project && python manage.py test --verbosity=2 django_gravatar

jobs:
  include:
    - python: "2.7"
      env:
        - DJANGO_VERSION=1.11
